##Sofía Ayala (12 de septiembre 2023)
1.- Considera el siguiente arreglo:
      x = arange(10)

2.- Realiza una segmentación para mostrar los valores de 4 a 7

3.- Usa el atributo np.split(x,[3,6]). Para x1, x2,x2 = np.split(x,[3,6]). ¿Qué valores te muestra?

4.- Considera la siguiente base de datos:
     data = pd.DataFrame({'Country':    ['Russia','Colombia','Chile','Equador','Nigeria'],'Rank':[121,40,100,130,11]})

5.- Del dataframe anterior, usa el atributo .info(). ¿Qué valores obtienes?

6.- Considera la siguiente base de datos:
    data = pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})
   (a) ¿Qué operaciones se está haciendo en los valores de las llaves.
   (b) Muestra la base de datos.

7.- Explica qué operación realiza el atributo .drop.duplicate()

8.- Explica, cuidadosamente, el data frame:
    data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['CDMX', 'Guanajuato', 'Puebla'],columns=['uno', 'dos', 'tres', 'cuatro'])

9.- Del dataframe anterior, renombre las etiquetas que provee Python sobre los renglones.

10. Explica el siguiente código:
 df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'], 'key2' : ['one', 'two', 'one', 'two', 'one'], 'data1' : np.random.randn(5),'data2' : np.random.randn(5)})
  (a) Quita la columna de "key 2".
  (b) Cambia el índice a tu conveniencia.
  (c) Realiza un análisis de estadística descriptiva (No es necesario explicar cada resultado).
  (d) Calcula la media de cada columna sobrante.

11.- (Opcional para punto extra). Toma una base de datos financiera (o créala) y realiza una serie de tiempo. Recuerda que una serie de tiempo depende de etiquetas de fechas y valores. Grafícala. ¿Qué observaciones obtienes?

In [22]:
#Paso 1
import pandas as pd
import numpy as  np
x= np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
#Paso 2
segmento= x[4:8]
print(segmento)


[4 5 6 7]


In [37]:
#Paso 3
np.split(x,[3,6])
x1,x2,x3 = np.split(x,[3,6])
print (x1,x2,x3)

[0 1 2] [3 4 5] [6 7 8 9]


In [67]:
#¿Qué valores muestra el paso 3? Esta divididiendo los valores del arange en tres listas

In [47]:
#Paso 4 y 5
data = pd.DataFrame({'Country': ['Russia','Colombia','Chile','Equador','Nigeria'],'Rank':[121,40,100,130,11]})
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Country  5 non-null      object
 1   Rank     5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


In [50]:
#5. ¿Qué valores obtienes? El data.info() nos muestra la información del DataFrame proporcionada por pandas, no por python.

In [68]:
#Paso 6
data=pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})
#(a) ¿Qué operaciones se está haciendo en los valores de las llaves.
#Lo que se esta haciendo dentro de las llaves es poniendo que datos van a ir en las columnas de k1 y k2, si los datos que estan entre corchetes estan multiplicados, esto quiere decir que se tienen que repetir ese número de veces.
#(b) Muestra la base de datos:
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [ ]:
#Paso 7
#.drop.duplicate()  Sirve para quitar las filas duplicadas


In [66]:
#Paso 8
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['CDMX', 'Guanajuato', 'Puebla'],columns=['uno', 'dos', 'tres', 'cuatro'])
data
#Asigna los nombres de las filas y las columnas con un index
#También usa un arange importado desde numpy para colocar los datos del 0 al 11 porque el arreglo es de 12
#Hace una matriz de 3X4 con el reshape

uno  dos  tres  cuatro
CDMX          0    1     2       3
Guanajuato    4    5     6       7
Puebla        8    9    10      11

In [71]:
# Paso 9.Del dataframe anterior, renombre las etiquetas que provee Python sobre los renglones.
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['Daniela', 'Sofía', 'Manuel'],columns=['uno', 'dos', 'tres', 'cuatro'])
data


uno  dos  tres  cuatro
Daniela    0    1     2       3
Sofía      4    5     6       7
Manuel     8    9    10      11

In [80]:
#Paso 10
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'], 'key2' : ['one', 'two', 'one', 'two', 'one'], 'data1' : np.random.randn(5),'data2' : np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one  2.033215 -0.092996
1    a  two -2.032402 -1.345288
2    b  one  1.375826 -1.015618
3    b  two -0.334508 -0.961053
4    a  one  0.822117  2.324785

In [83]:
#(a) Quita la columna de "key 2".
df1=df.drop(columns=["key2"])
df1

key1     data1     data2
0    a  2.033215 -0.092996
1    a -2.032402 -1.345288
2    b  1.375826 -1.015618
3    b -0.334508 -0.961053
4    a  0.822117  2.324785

In [97]:
#(b) Cambia el índice a tu conveniencia.
df=pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'], 'key2' : ['one', 'two', 'one', 'two', 'one'], 'data1': np.random.randn(5),'data2' : np.random.randn(5)},index=["Sofía","Farca","Manuel","Marado","Daniela"])
df

key1 key2     data1     data2
Sofía      a  one -1.044768 -0.649681
Farca      a  two -0.550078  0.826056
Manuel     b  one -0.742249 -0.546309
Marado     b  two -0.651073  0.859164
Daniela    a  one  0.036672 -0.072606

In [89]:
#(c) Realiza un análisis de estadística descriptiva (No es necesario explicar cada resultado).
df1.describe()

data1     data2
count  5.000000  5.000000
mean  -0.077301 -0.503131
std    1.009654  1.200152
min   -1.133771 -1.827189
25%   -0.792641 -1.688133
50%   -0.266310 -0.191394
75%    0.407310  0.380107
max    1.398907  0.810952

In [90]:
#(d) Calcula la media de cada columna sobrante
df1.mean()

<ipython-input-90-f0acf9c43727>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df1.mean()


data1   -0.077301
data2   -0.503131
dtype: float64